version: 0.2

phases:
  install:
    runtime-versions:
       docker: 18
       
  build:
    commands:
      - echo Build started on `date`      
      
artifacts:
     #encryptionDisabled: true
     files:
      - index.html      
     #discard-paths: yes  
     base-directory: ''
     
      
